[package]
name = "kubemc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
async-recursion = "1.0.0"
async-trait = "0.1.59"
clap = { version = "4.0.27", features = ["derive"] }
dirs = "4.0.0"
futures = "0.3.25"
k8s-openapi = { version = "0.16.0", features = ["v1_25"] }
kube = { version = "0.77.0", default-features = false, features = ["client", "config", "runtime", "rustls-tls"] }
regex = "1.7.0"
serde = { version = "1.0.148", features = ["std", "derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.14"
tabled = "0.10.0"
tokio = { version = "1.22.0", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
